config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :products do
    resources :sells
  end
  resources :sells, only: [:new, :create, :index, :show]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :sells, dependent: :destroy 

  validates :name, presence: true
  validates :price, presence: true
  has_one_attached :photo
end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :products, dependent: :destroy
  validates :total, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sells
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only:[:show, :edit , :update, :destroy]
  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @product.update!(product_params)
    redirect_to @product
  end

  def destroy
    @product.destroy!
    redirect_to products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :photo)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  def index
    @sells = Sell.includes(:products).all

  end

  def new
    @sell = Sell.new
    @products = Product.all
  end

  def show
    @sell = Sell.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name", template: "show.html.erb"   # Excluding ".pdf" extension.
      end
    end
  end

  def create
    @sell = Sell.new(sell_params)

    # Set the creation time
    @sell.created_at = Time.now

    # Assuming you have a method to calculate the total based on the product
    @sell.total = calculate_total(@sell.products)

    if @sell.save
      redirect_to sells_path
    else
      render 'new'
    end
  end

  private

  def sell_params
    params.require(:sell).permit(:product_id, :user_id, product_ids: [])
  end

  def calculate_total(product_ids)
    # Implement your logic to calculate the total based on the product
    # For example, you can sum the prices of selected products
    Product.where(id: product_ids).sum(&:price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleBees</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"></link>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <script src="https://kit.fontawesome.com/66b41dd09b.js" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: products_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="container d-flex justify-content-between">
  <%= link_to '/', class: 'btn btn-secondary mb-2' do %>
    <i class="fas fa-home"></i> Back home
  <% end %>

  <%= link_to new_product_path, class: 'btn btn-success mb-2' do %>
    <i class="fas fa-plus-circle"></i> Add new product
  <% end %>

  <%= link_to new_sell_path, class: 'btn btn-success' do %>
    <i class="fas fa-shopping-cart"></i> New Sell
  <% end %>
</div>

<div class="container">
  <h2 class="title">Product list</h2>

  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><%= product.name %></h2>
            <p class="card-text"><%= product.description %></p>
            <h3 class="card-text">$<%= product.price %></h3>
            <%= link_to product, class: 'btn btn-primary' do %>
              <i class="fas fa-info-circle"></i> More details
            <% end %>
            <%= link_to "/products/#{product.id}/sells/new", class: 'btn btn-success' do %>
              <i class="fas fa-shopping-cart"></i> Buy
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="center-form mt-5git a">
<%= simple_form_for @product do |f| %>
  <%= f.input :name, label: "Product Name", placeholder: "Enter product name"%>
  <%= f.input :description %>
  <%= f.input :price, as: :integer%>
  <%= f.input :photo, as: :file, input_html: { class: "custom-file-input" } %>
<div class="button-container">
<%= f.button :submit, "Create Product", class: "btn-success" %>
    <%= link_to '/', class: 'btn btn-secondary mb-2' do %>
      <i class="fas fa-home"></i> Back home
    <% end %>
    <%= link_to products_path, class: 'btn btn-primary mb-2 text-center' do %>
      <i class="fas fa-chevron-left"></i> Back to List
    <% end %>
</div>
<% end %>
</div>

app/views/products/show.html.erb
<div class='container'>
    <%= link_to products_path, class: 'btn btn-primary mb-2 text-center' do %>
      <i class="fas fa-chevron-left"></i> Back to List
    <% end %>
  </div>
  <div class='container d-flex justify-content-center'>
      <div class="col-md-4 mb-4">
        <div class="card">
          <%# <%= cl_image_tag @product.photo.key, class: "card-img-top" if @product.photo.attached? %>
          <div class="card-body">
            <h2 class="card-title"><%= @product.name %></h2>
            <p class="card-text"><%= @product.description %></p>
            <h3 class="card-text">$<%= @product.price %></h3>
            <%= link_to edit_product_path, class: 'btn btn-primary' do %>
            <i class="fas fa-edit"></i> Edit
            <% end %>
            <%= link_to "/products/#{@product.id}/sells/new", class: 'btn btn-success' do %>
              <i class="fas fa-shopping-cart"></i> Buy
            <% end%>
            <%= link_to @product, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to permanently delete this product?' } do %>
              <i class="fas fa-trash-alt"></i> Delete
            <% end %>
          </div>
        </div>
      </div>
</div>

app/views/sells/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center">Sells</h2>

<% @sells.reverse_each.with_index(1) do |sell, index| %>
  <div class="card mb-2">
    <div class="card-body">
      <h6 class="card-title">
        <%= "#{index}. Sell ID: #{sell.id}" %><br>
        <%= "#{sell.products.size} Products:" %><br>
        <% sell.products.each do |product| %>
          <%= "#{product.name.capitalize} - $#{product.price}" %><br>
        <% end %>
      </h6>
      <p class="card-text">
        <span class="float-left">
          <% if sell.created_at.present? %>
            Comprado el: <%= sell.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
          <% else %>
            Comprado el: N/A
          <% end %>
        </span>
      </p>
    </div>
  </div>
<% end %>

      <div class='container'>
        <%= link_to products_path, class: 'btn btn-success mb-2 text-center' do %>
          <i class="fas fa-cart-arrow-down"></i> Back to List
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sells/new.html.erb
<%= simple_form_for(@sell) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>



<%= label_tag 'products', 'Products', class: 'fs-4 mt-1 mb-1' %>
 <%= select_tag 'sell[product_ids][]', options_for_select(Product.all.map { |product| [product.name, product.id] }), class: 'fs-4 mt-2 mb-3 p-1 slim-select', data: { controller: 'dropdown' }, multiple: true %>
  <%= label_tag 'user', 'Select User', class: 'fs-4 mt-1 mb-1' %>
  <%= f.input :user, as: :select, collection: @users, input_html: { data: { controller: 'dropdown' } } %>


    <%= f.submit 'Create Sell', class: 'btn btn-success' %>
    <%= link_to "Cancel", sells_path, class: "btn btn-danger" %>
<% end %>

app/views/sells/show.html.erb
<h1>HOla</h1>
<%=  @sell %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light ">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>